title: Carlo Acutis Ireland
description: National representation of Carlo Acutis in Ireland
baseurl: "/carlo-acutis-ireland"
url: "https://alanmaizon.github.io/carlo-acutis-ireland/"
theme: minima
plugins:
  - jekyll-feed
